sudo: required
services:
  - docker

before_install:
  - docker build -t karan4336/multi-docker-client-dev -f ./client/Dockerfile.dev ./client  

script:
  - docker run -e CI=true karan4336/multi-docker-client-dev npm run test

after_success:
  - docker build -t karan4336/multi-docker-client ./client  
  - docker build -t karan4336/multi-docker-nginx ./nginx  
  - docker build -t karan4336/multi-docker-server ./server  
  - docker build -t karan4336/multi-docker-worker ./worker

# Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# push images to docker hub
  - docker push karan4336/multi-docker-client
  - docker push karan4336/multi-docker-nginx
  - docker push karan4336/multi-docker-server
  - docker push   karan4336/multi-docker-worker